const mongoose = require("mongoose");

const branches = new mongoose.Schema(
    {
        branch:{
            type:String,
            required:true,
            maxLength:255,
        },
        country:{
            type:String,
            required:true,
            maxLength:255,
        },
        city:{
            type:String,
            required:true,
            maxLength:255,
        },
        name:{
            type:String,
            required:true,
            maxLength:255,
        },
        email:{
            type:String,
            required:false,
            maxLength:255,
        },
        phone:{
            type:String,
            required:true,
            maxLength:255,
        },
        currency:{
            type:String,
            required:true,
            maxLength:255,
        },
        timeZone:{
            type:String,
            required:true,
            maxLength:255,
        },
        creditLimit:{
            type:String,
            required:true,
            maxLength:255,
        },
        remitLimit:{
            type:String,
            required:true,
            maxLength:255,
        },
        payAgent:{
            type:String,
            required:true,
            maxLength:255,
        },
        remitAgent:{
            type:String,
            required:true,
            maxLength:255,
        },
        payCurrency:{
            type:String,
            required:true,
            maxLength:255,
        },
        remitCurrency:{
            type:String,
            required:true,
            maxLength:255,
        },
        payCurrency:{
            type:String,
            required:true,
            maxLength:255,
        },
        balanceBy:{
            type:String,
            required:false,
            maxLength:255,
        },
        remark:{
            type:String,
            required:false,
            maxLength:255,
        },
        info:{
            type:String,
            required:false,
            maxLength:2000,
        },
        isActive:{
            type:Boolean,
            default:false,
        },
    }
);
module.exports = mongoose.model("Branch", branches);